import faker from "faker";

export const GeneratorLib = {
  string: faker.datatype.string,
  text: faker.lorem.text,
  words: faker.lorem.words,
  sentance: faker.lorem.sentence,
  number: faker.datatype.number,
  boolean: faker.datatype.boolean,
  datetime: faker.datatype.datetime,
  pastdate: faker.date.past,
  futuredate: faker.date.future,
  uuid: faker.datatype.uuid,
  userName: faker.internet.userName,
  avartar: faker.image.avatar,
  firstName: faker.name.firstName,
  lastName: faker.name.lastName,
  fullName: faker.name.findName,
  phone: faker.phone.phoneNumber,
  email: faker.internet.email,
  exampleEmail: faker.internet.exampleEmail,
  password: faker.internet.password,
  streetAddress: faker.address.streetAddress,
  city: faker.address.city,
  state: faker.address.state,
  state_abbr: faker.address.stateAbbr,
  zipcode: faker.address.zipCode,
  country: faker.address.country,
  timezone: faker.address.timeZone,
  price: faker.commerce.price,
  sentence: faker.lorem.sentence,
};
